---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
#  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[fixtures]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
      tomcat:
        base_version: 6